version: "3.8"

services:
  web:
    build: .
    image: ghcr.io/mimrankhandjango/quran_academy:latest
    container_name: quran_academy_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - .:/app
    command: ["gunicorn", "quran_academy.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]

volumes:
  static_volume:
